[info]
name         = "CustomIDAutonumber"
description  = "アイテム保存時にPACKAGE0000001のようなシリアル連番を自動採番します。"
version      = "1.0.0"
author       = "Kazufumi Fukuda"
; omeka_version_constraint = "^3.0.0 || ^4.0.0" ; お使いのOmeka Sのバージョンに合わせて調整してください
