# GitHub Pages Jekyll Configuration

# Site settings
title: "RCGS Archive Data Tools"
description: "立命館大学ゲーム研究センター アーカイブデータ・ツール ドキュメントサイト"
baseurl: "/data-tools"
url: "https://rcgs-archive.github.io"

# Author information
author: "立命館大学ゲーム研究センター"
email: "contact@rcgs.jp"

# Footer information
footer_name: "立命館大学ゲーム研究センター"
footer_email: "contact@rcgs.jp"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation menu
header_pages:
  - schema/index.md
  - tools/index.md
  - api/index.md

# Collections for organizing content
collections:
  schema:
    output: true
    permalink: /:collection/:name/
  tools:
    output: true
    permalink: /:collection/:name/
  api:
    output: true
    permalink: /:collection/:name/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages

# GitHub Pages specific settings
github:
  repository_url: "https://github.com/rcgs-archive/data-tools"
  repository_name: "data-tools"

# SEO and social
twitter:
  username: rcgs_archive
  card: summary

social:
  name: RCGS
  links:
    - https://github.com/rcgs-archive/data-tools
